c_compiler_version: # works in conjunction with c_stdlib_version
  - 12          # [linux and aarch64]
  - 12          # [linux and x86_64]

cxx_compiler_version:
  - 12          # [linux and aarch64]
  - 12          # [linux and x86_64]

c_stdlib_version:
  - 2.28        # [linux and aarch64]
  - 2.28        # [linux and x86_64]

fortran_compiler_version:
  - 12          # [linux and aarch64]
  - 12          # [linux and x86_64]

cuda_compiler_version:
  - 12.0        # [linux and aarch64]
  - 12.0        # [linux and x86_64]

cuda_compiler:
  - cuda-nvcc   # [linux and aarch64]
  - cuda-nvcc   # [linux and x86_64]

docker_image:
  - quay.io/condaforge/linux-anvil-alma-aarch64:8     # [linux and aarch64] # glibc 2.28
  - quay.io/condaforge/linux-anvil-alma-x86_64:8      # [linux and x86_64]  # glibc 2.28
